### ISSUE TITLE
I was trying to make a zombie apocolypse mod (will add BadMods later) but for some reason everytime i make the world, it just crashes. heres the crash log. Everything works just fine and only crashes when i put wastelands in

### ISSUE THREAD

**Issue by EnderGamer190** [Hennamann/Wasteland#26]

**Comment by EnderGamer190** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/31/21 8:23 PM
Description: Exception initializing level

java.lang.NullPointerException: Exception initializing level
	at net.minecraft.util.math.ChunkPos.<init>(ChunkPos.java:25)
	at net.minecraftforge.event.terraingen.DecorateBiomeEvent$Post.<init>(DecorateBiomeEvent.java:130)
	at com.legacy.wasteland.world.biome.decorations.BiomeDecoratorWasteland.func_150513_a(BiomeDecoratorWasteland.java:141)
	at com.legacy.wasteland.world.biome.decorations.BiomeDecoratorWasteland.func_180292_a(BiomeDecoratorWasteland.java:98)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at com.legacy.wasteland.world.ChunkGeneratorWasteland.func_185931_b(ChunkGeneratorWasteland.java:359)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.math.ChunkPos.<init>(ChunkPos.java:25)
	at net.minecraftforge.event.terraingen.DecorateBiomeEvent$Post.<init>(DecorateBiomeEvent.java:130)
	at com.legacy.wasteland.world.biome.decorations.BiomeDecoratorWasteland.func_150513_a(BiomeDecoratorWasteland.java:141)
	at com.legacy.wasteland.world.biome.decorations.BiomeDecoratorWasteland.func_180292_a(BiomeDecoratorWasteland.java:98)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at com.legacy.wasteland.world.ChunkGeneratorWasteland.func_185931_b(ChunkGeneratorWasteland.java:359)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 94 Drop: 0
	Level seed: 1417083266508661151
	Level generator: ID 06 - wasteland, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 200573704 bytes (191 MB) / 463724544 bytes (442 MB) up to 3075735552 bytes (2933 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx2945M -XX:+UseConcMarkSweepGC
	IntCache: cache: 8, tcache: 76, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version        | Source                                      | Signature                                |
	|:------ |:---------------- |:-------------- |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2         | minecraft.jar                               | None                                     |
	| LCHIJA | mcp              | 9.42           | minecraft.jar                               | None                                     |
	| LCHIJA | FML              | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit        | 1.3.3-1.12     | minecraft.jar                               | None                                     |
	| LCHIJA | extendedrenderer | v1.0           | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | coroutil         | 1.12.1-1.2.37  | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | configmod        | v1.0           | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | ichunutil        | 7.2.2          | iChunUtil-1.12.2-7.2.2.jar                  | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mobdismemberment | 7.0.0          | MobDismemberment-1.12.2-7.0.0.jar           | None                                     |
	| LCHIJA | toughasnails     | 3.1.0.139      | ToughAsNails-1.12.2-3.1.0.139-universal.jar | None                                     |
	| LCHIJA | wastelands       | 1.2.2          | Wastelands-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | zombieawareness  | 1.12.1-1.11.16 | zombieawareness-1.12.1-1.11.16.jar          | None                                     |

	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6170
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
