### ISSUE TITLE
[1.12.2] Crashing on server

### ISSUE THREAD

**Issue by MarioSMB** [Hennamann/Wasteland#5]
Getting a crash when loading this mod on a dedicated server:

[05:15:00] [Server thread/ERROR] [FML]: Caught exception from wastelands (Wasteland Mod)  
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderLivingBase

**Comment by Hennamann** [comment]
What version of the mod, and what forge version? and send a full crash report, it's hard to track down the issue without the full stack trace.

**Comment by MarioSMB** [comment]
Running latest version of the wastelands and Forge 1.12.2-14.23.2.2629, here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 3/19/18 10:33 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wasteland Mod (wastelands)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderLivingBase
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:127)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:111)
	at com.legacy.wasteland.Wasteland.registerEvent(Wasteland.java:46)
	at com.legacy.wasteland.Wasteland.init(Wasteland.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.RenderLivingBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@6bcbf05b from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 46 more
Caused by: java.lang.RuntimeException: Attempted to load class caa for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 48 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-103-generic
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 431715336 bytes (411 MB) / 1215549440 bytes (1159 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 3 total; -Xms512M -Xmx4G -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2629 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                     | Source                                        | Signature                                |
	|:----- |:------------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                 | 1.12.2                      | minecraft.jar                                 | None                                     |
	| UCHI  | mcp                       | 9.42                        | minecraft.jar                                 | None                                     |
	| UCHI  | FML                       | 8.0.99.99                   | forge-1.12.2-14.23.2.2629-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                     | 14.23.2.2629                | forge-1.12.2-14.23.2.2629-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | spongeapi                 | 7.1.0-SNAPSHOT-06016f2      | spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar   | None                                     |
	| UCHI  | sponge                    | 1.12.2-2611-7.1.0-BETA-2970 | spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar   | None                                     |
	| UCHI  | codechickenlib            | 3.1.5.331                   | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | mercurius_updater         | 1.0                         | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHI  | craftirc                  | 4.2.0                       | craftirc-4.2.0.jar                            | None                                     |
	| UCHI  | nucleus                   | 1.3.4-S7.0                  | Nucleus-1.3.4-S7.0-MC1.12.2-plugin.jar        | None                                     |
	| UCHI  | pjc                       | 0.2.1                       | projectcore-7.0.0-0.2.1.jar                   | None                                     |
	| UCHI  | pji                       | 0.11.2                      | projectinventories-7.1.0-0.11.2.jar           | None                                     |
	| UCHI  | pjp                       | 0.14.3                      | projectportals-7.1.0-0.14.3.jar               | None                                     |
	| UCHI  | pjw                       | 0.12.2                      | projectworlds-7.1.0-0.12.2.jar                | None                                     |
	| UCHI  | actuallyadditions         | 1.12.2-r132                 | ActuallyAdditions-1.12.2-r132.jar             | None                                     |
	| UCHI  | aether_legacy             | 1.12.2-v2.0                 | aether_legacy-1.12.2-v2.0.jar                 | None                                     |
	| UCHI  | aroma1997core             | 2.0.0.0.b148                | Aroma1997Core-1.12.2-2.0.0.0.b148.jar         | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHI  | aromabackup               | 2.1.1.3.b94                 | AromaBackup-1.12.2-2.1.1.3.b94.jar            | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHI  | aromabackuprecovery       | 2.1.1.3.b94                 | AromaBackup-1.12.2-2.1.1.3.b94.jar            | None                                     |
	| UCHI  | quark                     | r1.4-122                    | Quark-r1.4-122.jar                            | None                                     |
	| UCHI  | autoreglib                | 1.3-15                      | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCHI  | biomesoplenty             | 7.0.1.2325                  | BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| UCHI  | buildcraftlib             | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcraftcore            | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcraftbuilders        | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcraftenergy          | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcraftfactory         | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcraftrobotics        | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcraftsilicon         | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | buildcrafttransport       | 7.99.15                     | buildcraft-7.99.15.jar                        | None                                     |
	| UCHI  | chameleon                 | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHI  | chisel                    | MC1.12.2-0.2.0.31           | Chisel-MC1.12.2-0.2.0.31.jar                  | None                                     |
	| UCHI  | crafttweaker              | 4.1.6                       | CraftTweaker2-1.12-4.1.6.jar                  | None                                     |
	| UCHI  | crafttweakerjei           | 2.0.0                       | CraftTweaker2-1.12-4.1.6.jar                  | None                                     |
	| UCHI  | customspawner             | 3.11.4                      | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| UCHI  | mocreatures               | 12.0.4                      | DrZharks MoCreatures Mod-12.0.4.jar           | None                                     |
	| UCHI  | erebus                    | 1.0.21                      | Erebus-1.0.21.jar                             | None                                     |
	| UCHI  | flansmod                  | 5.5.2                       | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| UCHI  | flansmodapocalypse        | 1.0                         | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| UCHI  | ichunutil                 | 7.1.4                       | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHI  | hats                      | 7.0.0                       | Hats-1.12.2-7.0.2.jar                         | None                                     |
	| UCHI  | mantle                    | 1.12-1.3.1.21               | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHI  | natura                    | 1.12.2-4.3.2.42             | natura-1.12.2-4.3.2.42.jar                    | None                                     |
	| UCHI  | nex                       | 2.1.14.15                   | NetherEx-1.12-2.1.14.15.jar                   | None                                     |
	| UCHI  | harvestcraft              | 1.12.2r                     | Pam's+HarvestCraft+1.12.2r.jar                | None                                     |
	| UCHI  | radixcore                 | 1.12.x-2.2.1                | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHI  | redstoneflux              | 2.0.1                       | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHI  | reforged                  | 0.7.5                       | Reforged-0.7.5-1.12+.jar                      | None                                     |
	| UCHI  | com.superzanti.serversync | 2.6.16                      | serversync-2.6.16-alpha.2.jar                 | None                                     |
	| UCHI  | storagedrawers            | 1.12-5.2.5                  | StorageDrawers-1.12.2-5.3.5.jar               | None                                     |
	| UCHI  | tconstruct                | 1.12.2-2.9.1.65             | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCHI  | twilightforest            | 3.6.345                     | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |
	| UCHE  | wastelands                | 1.2.2                       | Wastelands-1.12-1.2.2-9-universal.jar         | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Hennamann** [comment]
I've made some code changes that should fix the issue, but I have not had the time to test them, could you test this build and tell me if the issue has been fixed? 
https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-10/Wastelands-1.12-1.2.2-10-universal.jar

**Comment by MarioSMB** [comment]
The issue does indeed appear to be fixed there, server starts normally, thanks.

**Comment by Hennamann** [comment]
Awesome! I'll get the build uploaded to Curse fairly soon then!
